const express = require('express');
const cors = require('cors');
const mongoose = require('mongoose');
require('dotenv').config();

const app = express();
const PORT = process.env.PORT || 5000;

app.use(cors());
app.use(express.json({ limit: '50mb' }));
app.use(express.urlencoded({ limit: '50mb', extended: true }));

// Connect to MongoDB
const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://127.0.0.1:27017/cglprepai';
mongoose.connect(MONGODB_URI, {
  useNewUrlParser: true,
  useUnifiedTopology: true
}).then(() => console.log('MongoDB Connected'))
  .catch(err => console.error('MongoDB connection error:', err));

// Routes
app.use('/api/auth', require('./routes/auth'));
app.use('/api/dashboard', require('./routes/dashboard'));
app.use('/api/ai', require('./routes/ai'));
app.use('/api/progress', require('./routes/progress'));
app.use('/api/studyplan', require('./routes/studyplan'));

// Dynamic Page Data Engine
const { getDailyNews } = require('./utils/currentAffairsEngine');

const REVIEWS = [
  { id: 1, tab: 'CGL Selected', name: 'Amit Sharma', role: 'Tax Assistant, CGL 2024', text: '"CGLPrep AI\'s mock tests and analysis helped me improve over 30% in 3 months. The AI study plan is amazing!"', rating: 5 },
  { id: 2, tab: 'CGL Selected', name: 'Priya Kumari', role: 'Auditor, CGL 2024', text: '"The post prediction feature gave me clarity. I could plan my preparation & target post & confidence."', rating: 5 },
  { id: 3, tab: 'CGL Selected', name: 'Rahul Verma', role: 'Inspector, CGL 2024', text: '"Best platform for the serious aspirants. Notes, tests, current affairs – everything in one place."', rating: 4.5 },
  { id: 4, tab: 'Home For Aspirants', name: 'Sanjay', role: 'Aspirant', text: '"The AI driven study plan adjusts perfectly to my weak areas in Quant."', rating: 5 },
  { id: 5, tab: 'Home For Aspirants', name: 'Neha', role: 'Aspirant', text: '"Daily news generated by AI is extremely relevant and saves a lot of time."', rating: 4.5 },
  { id: 6, tab: 'Expert Views', name: 'R. K. Singh', role: 'Ex-Income Tax Officer', text: '"The level of mock tests exactly mimics TCS pattern. Highly recommended."', rating: 5 },
  { id: 7, tab: 'Authors', name: 'Vikash Sir', role: 'Maths Expert', text: '"The mistake book feature is a game changer for students making silly errors."', rating: 5 },
];

app.get('/api/page-data/:pageId', (req, res) => {
  const pageId = req.params.pageId;
  
  if (pageId === 'home') {
    // Generate realistic, growing stats based on the date
    const today = new Date();
    const dayOfYear = Math.floor((today - new Date(today.getFullYear(), 0, 0)) / 86400000);
    const baseLearners = 100000 + (dayOfYear * 150);
    
    const homeData = {
      heroTitle: "Crack CGL 2026 with AI",
      stats: {
        activeLearners: baseLearners.toLocaleString(),
        questionsPracticed: (baseLearners * 10).toLocaleString(),
        mockTestsAttempted: Math.floor(baseLearners * 0.5).toLocaleString(),
        improvementRate: "90%",
        rating: "4.8/5"
      },
      topNews: getDailyNews(today.toISOString().split('T')[0], 3),
      reviews: REVIEWS
    };
    
    return res.json({ success: true, data: homeData });
  }

  res.status(404).json({ success: false, message: 'Page data not found' });
});

// Original Status Route
app.get('/api/status', (req, res) => {
    res.json({ message: 'Backend is running successfully!', status: 'OK' });
});

app.listen(PORT, () => {
    console.log(`Server running on port ${PORT}`);
});

// Triggering nodemon restart
